# .github/workflows/ci-cd.yml
name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        
    - name: Train model
      run: |
        cd backend/src
        python train_model.py
        
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -H "Authorization: Bearer $RENDER_API_KEY" \
             -H "Content-Type: application/json" \
             -X POST https://api.render.com/v1/services \
             -d '{
               "name": "personal-finance-assistant",
               "type": "web_service",
               "env": "python",
               "buildCommand": "pip install -r requirements.txt",
               "startCommand": "gunicorn app:app"
             }'